### ISSUE TITLE
Wiring List (spreadsheet)

### ISSUE THREAD

**Issue by Josiah-V** [AGHSEagleRobotics/frc1388-2020#19]
The wiring and placement of electronic components and sensors needs to be tracked. This will be done with a spreadsheet linked here: https://docs.google.com/spreadsheets/d/1-_TZ13xsfVZVFzq8rJBhIH7Ht_RBKVlgj4VI8T67ISo/edit#gid=0

This needs to be updated regularly to ensure good communication and planning.

**Comment by jtechau** [comment]
Josiah, I've updated the spreadsheet with the columns that I think will be most useful to programming, electrical and design.  We may want to add more columns later, for example if it's useful to define subsystems, commands, controls, etc.  It may be more appropriate to define those details on wiki pages, but we can figure that out.  The most important aspect of this spreadsheet is to list all elements on the robot that need to be agreed upon and understood by design, electrical and programming.

I filled in some examples, but you'll still need to work with design and electrical on the remaining details.
